# Generated by Django 5.0.7 on 2024-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_monitorias_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauser',
            name='monitorias_ausentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datauser',
            name='monitorias_canceladas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datauser',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
