# Generated by Django 5.0.7 on 2024-11-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_datauser_monitorias_ausentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='status',
            field=models.CharField(choices=[('AUSENTE', 'Ausente'), ('PRESENTE', 'Presente'), ('CANCELADA', 'Cancelada')], default='MARCADA', max_length=15),
        ),
    ]
